# Generated by Django 4.0.4 on 2022-04-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_slug_category_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
