# Generated by Django 4.0.4 on 2022-04-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_category_slug_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categroy',
            new_name='category',
        ),
    ]
