# Generated by Django 4.0.4 on 2022-04-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_categroy_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='productimage',
        ),
    ]
