# Generated by Django 4.0.4 on 2022-04-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_product_image_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productimage',
            new_name='product_image',
        ),
    ]
