# Generated by Django 4.0.4 on 2022-05-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='details',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='happy',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='satisfied',
        ),
    ]
